### ISSUE TITLE
Keep n ASTrees

### ISSUE THREAD

**Issue by franziskuskiefer** [raphaelrobert/maelstrom#16]
The group should keep the last `n` applications secret trees.

https://github.com/raphaelrobert/maelstrom/blob/ac0ea4d01af7ebe616abf85cd7531a89a3ce4263/src/group/mls_group/mod.rs#L43

**Comment by kkohbrok** [comment]
Where `n` is the number of epochs we want to keep material around for to be able to receive late messages?

**Comment by franziskuskiefer** [comment]
Right, `n` should be `OUT_OF_ORDER_TOLERANCE`.
https://github.com/raphaelrobert/maelstrom/blob/ac0ea4d01af7ebe616abf85cd7531a89a3ce4263/src/astree.rs#L23

**Comment by raphaelrobert** [comment]
If we enforce the rule that Application Messages must have the correct epoch ID, we can actually drop this requirement.

**Comment by franziskuskiefer** [comment]
I'd prefer that. Please file an issue for it and close this one.

**Comment by raphaelrobert** [comment]
Filed in https://github.com/wireapp/security/issues/54.
